import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { getResend, sendInboundEmailNotification } from '@/lib/email'
import { getSenderDomain, parseInboundAddress } from '@/lib/email-identity'
import { verifySvixSignature } from '@/lib/webhook-verify'
import { logAudit } from '@/lib/audit'

const BODY_LIMIT = 20000
const SNIPPET_LIMIT = 400

interface InboundMail {
  id: string
  from: string
  to: string[]
  received_for: string[]
  subject: string
  text: string | null
  html: string | null
  headers: Record<string, string> | null
  attachments: Array<{ filename?: string | null; content_type?: string | null; size?: number | null }>
}

/** "Jane Doe <jane@x.com>" -> { name: 'Jane Doe', email: 'jane@x.com' } */
function parseFrom(from: string): { name: string | null; email: string } {
  const match = from.match(/^\s*(?:"?([^"<]*)"?\s*)?<([^>]+)>\s*$/)
  if (match) return { name: match[1]?.trim() || null, email: match[2].trim().toLowerCase() }
  return { name: null, email: from.trim().toLowerCase() }
}

function htmlToText(html: string): string {
  return html
    .replace(/<(style|script)[\s\S]*?<\/\1>/gi, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|tr|li|h[1-6])>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/** Out-of-office and other machine-generated mail must not create enquiries. */
function isAutoGenerated(headers: Record<string, string> | null): boolean {
  if (!headers) return false
  const lower = Object.fromEntries(
    Object.entries(headers).map(([k, v]) => [k.toLowerCase(), String(v).toLowerCase()])
  )
  if (lower['auto-submitted'] && lower['auto-submitted'] !== 'no') return true
  if ('x-autoreply' in lower || 'x-autorespond' in lower) return true
  const precedence = lower['precedence']
  return precedence === 'bulk' || precedence === 'auto_reply' || precedence === 'junk'
}

async function notifyProjectAdmins(args: {
  projectId: string
  projectName: string
  kind: 'reply' | 'new'
  fromName: string | null
  fromEmail: string
  subject: string
  snippet: string
}) {
  // Super admins have implicit access to every project, so they're alerted
  // alongside the project's own admins.
  const [access, superAdmins] = await Promise.all([
    prisma.projectAccess.findMany({
      where: { projectId: args.projectId, role: 'ADMIN' },
      select: { user: { select: { email: true } } },
    }),
    prisma.user.findMany({
      where: { systemRole: 'SUPER_ADMIN' },
      select: { email: true },
    }),
  ])
  const to = Array.from(
    new Set(
      [...access.map(a => a.user.email), ...superAdmins.map(u => u.email)].filter(
        (e): e is string => Boolean(e)
      )
    )
  )
  if (to.length === 0 && process.env.CONTACT_NOTIFY_EMAIL) {
    to.push(process.env.CONTACT_NOTIFY_EMAIL)
  }
  const baseUrl = (process.env.NEXTAUTH_URL || 'https://platform.placemakerai.io').replace(/\/$/, '')
  await sendInboundEmailNotification({ ...args, to, baseUrl })
}

/**
 * Resend `email.received` webhook: routes inbound mail on the platform domain
 * into the enquiries inbox. Recipient addresses resolve by their tag —
 * `<project>+e-<threadToken>@` appends to that enquiry's thread,
 * `<project>+c-<campaignId>@` and bare `<project>@` create a new email-channel
 * enquiry. Unknown addresses are acknowledged and dropped (a 200 stops Resend
 * retrying; spam to guessed addresses must not 500 the endpoint).
 */
export async function POST(request: Request) {
  const secret = process.env.RESEND_WEBHOOK_SECRET
  if (!secret) {
    return NextResponse.json({ error: 'Inbound email not configured' }, { status: 503 })
  }

  const payload = await request.text()
  const verified = verifySvixSignature({
    secret,
    id: request.headers.get('svix-id'),
    timestamp: request.headers.get('svix-timestamp'),
    signature: request.headers.get('svix-signature'),
    payload,
  })
  if (!verified) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 })
  }

  let event: { type?: string; data?: { email_id?: string; id?: string } }
  try {
    event = JSON.parse(payload)
  } catch {
    return NextResponse.json({ error: 'Invalid payload' }, { status: 400 })
  }
  if (event.type !== 'email.received') return NextResponse.json({ ok: true })

  const emailId = event.data?.email_id ?? event.data?.id
  if (!emailId) return NextResponse.json({ ok: true })

  // Webhook deliveries retry; the same inbound email must only land once.
  const [seenMessage, seenEnquiry] = await Promise.all([
    prisma.enquiryMessage.findUnique({ where: { externalId: emailId }, select: { id: true } }),
    prisma.enquiry.findUnique({ where: { externalId: emailId }, select: { id: true } }),
  ])
  if (seenMessage || seenEnquiry) return NextResponse.json({ ok: true, deduped: true })

  const domain = getSenderDomain()
  const client = getResend()
  if (!domain || !client) return NextResponse.json({ ok: true })

  const { data, error } = await client.emails.receiving.get(emailId)
  if (error || !data) {
    console.error('Inbound: failed to fetch received email', emailId, error)
    // 500 so Resend retries — the email exists, we just couldn't read it yet.
    return NextResponse.json({ error: 'Fetch failed' }, { status: 500 })
  }
  const mail = data as unknown as InboundMail

  if (isAutoGenerated(mail.headers)) {
    return NextResponse.json({ ok: true, skipped: 'auto-generated' })
  }

  const recipients = (mail.received_for?.length ? mail.received_for : mail.to) ?? []
  const parsed = recipients
    .map(address => parseInboundAddress(address, domain))
    .find(Boolean)
  if (!parsed) return NextResponse.json({ ok: true, skipped: 'no recipient on domain' })

  const from = parseFrom(mail.from)
  const body =
    (mail.text?.trim() || (mail.html ? htmlToText(mail.html) : '') || '(no content)').slice(0, BODY_LIMIT)
  const snippet = body.slice(0, SNIPPET_LIMIT)
  const subject = mail.subject?.trim() || '(no subject)'
  const attachments = mail.attachments?.length
    ? mail.attachments.map(a => ({
        name: a.filename ?? 'attachment',
        size: a.size ?? null,
        mime: a.content_type ?? null,
      }))
    : undefined

  // Thread reply: tag carries the enquiry's unguessable threadToken.
  if (parsed.tag?.startsWith('e-')) {
    const enquiry = await prisma.enquiry.findUnique({
      where: { threadToken: parsed.tag.slice(2) },
      include: { project: { select: { id: true, name: true } } },
    })
    if (!enquiry) return NextResponse.json({ ok: true, skipped: 'unknown thread' })

    await prisma.enquiryMessage.create({
      data: {
        enquiryId: enquiry.id,
        direction: 'inbound',
        body,
        authorName: from.name,
        authorEmail: from.email,
        deliveryStatus: 'delivered',
        attachments,
        externalId: emailId,
      },
    })
    await prisma.enquiry.update({
      where: { id: enquiry.id },
      data: { read: false, status: enquiry.status === 'closed' ? 'open' : enquiry.status },
    })
    await logAudit({
      projectId: enquiry.project.id,
      action: 'enquiry.inbound',
      targetType: 'enquiry',
      targetId: enquiry.id,
      detail: { emailId, from: from.email },
    })
    await notifyProjectAdmins({
      projectId: enquiry.project.id,
      projectName: enquiry.project.name,
      kind: 'reply',
      fromName: from.name,
      fromEmail: from.email,
      subject: enquiry.subject,
      snippet,
    })
    return NextResponse.json({ ok: true, threaded: enquiry.id })
  }

  // Campaign reply or direct mail to the project address: new email enquiry.
  let project: { id: string; name: string } | null = null
  if (parsed.tag?.startsWith('c-')) {
    const campaign = await prisma.campaign.findUnique({
      where: { id: parsed.tag.slice(2) },
      select: { project: { select: { id: true, name: true } } },
    })
    project = campaign?.project ?? null
  }
  if (!project) {
    project = await prisma.project.findUnique({
      where: { emailLocalPart: parsed.localPart },
      select: { id: true, name: true },
    })
  }
  if (!project) return NextResponse.json({ ok: true, skipped: 'unknown address' })

  const enquiry = await prisma.enquiry.create({
    data: {
      projectId: project.id,
      submitterName: from.name ?? from.email,
      submitterEmail: from.email,
      subject,
      message: body,
      channel: 'email',
      externalId: emailId,
    },
  })
  await logAudit({
    projectId: project.id,
    action: 'enquiry.inbound',
    targetType: 'enquiry',
    targetId: enquiry.id,
    detail: { emailId, from: from.email, viaCampaign: parsed.tag?.startsWith('c-') ?? false },
  })
  await notifyProjectAdmins({
    projectId: project.id,
    projectName: project.name,
    kind: 'new',
    fromName: from.name,
    fromEmail: from.email,
    subject,
    snippet,
  })
  return NextResponse.json({ ok: true, enquiry: enquiry.id })
}
